### ISSUE TITLE
Multiple pixel id for difference URL path

### ISSUE THREAD

**Issue by puuga** [WilliamDASILVA/nuxt-facebook-pixel-module#11]
I got a problem with the multiple PixelId situation.
for example, when route is at / will use default PixelId.
when route is at /a/* will use PixelId a.
when route is at /b/* will use PixelId b.

To handle these, if plugin has a path option for determine which PixelId match to the path 
```javascript
facebook: [
  {
    /* module option a */
    track: 'PageView',
    pixelId: 'FACEBOOK_PIXEL_ID_A',
    disabled: false,
    path: '/a/*', // will use this option when path is http://foo.bar/a
  },
  {
    /* module option b */
    track: 'PageView',
    pixelId: 'FACEBOOK_PIXEL_ID_B',
    disabled: false,
    path: '/b/*', // will use this option when path is http://foo.bar/b
  },
  {  // will use this option when path are others
    /* module option default */
    track: 'PageView',
    pixelId: 'FACEBOOK_PIXEL_ID_DEFAULT',
    disabled: false,
  },
],
```

Or can change pixel on the fly with `$fb.init('pixelId')` or `$fb.pixelId('pixelId')`

Anyway, I'm looking for the possible methods to handle this.

Thanks 😊

**Comment by drewbaker** [comment]
I would love a way to be able to use multiple pixels, but don't need the different path feature (although I see why that would be useful).

**Comment by sts-ryan-holton** [comment]
Will this work?

**Comment by wasinr** [comment]
@puuga please share is this method work? I would like to put FB pixel dynamically on each page also.

Regards.

**Comment by djcheung** [comment]
FYI - I got this to work inside of the nuxt life cycle hooks (for my example I did it in the created() {} with disabled = true in the nuxt.config.js) with the following:

```
this.$fb.query('init', 'your pixel code');
this.$fb.track('PageView');
this.$fb.enable();
```

**Comment by rahulmukati** [comment]
+1 for multiple pixels support in this module!

**Comment by WilliamDASILVA** [comment]
Hello there,

Thank you for taking the time to make this issue.
I've added a `pixels` property to specify multiple pixels according to the route in the release `v1.4.0`.
See more at https://github.com/WilliamDASILVA/nuxt-facebook-pixel-module#multiple-pixel-codes-according-to-route

Let me know if you have any further issues with that.
