### ISSUE TITLE
$fb.disable() method

### ISSUE THREAD

**Issue by HapLifeMan** [WilliamDASILVA/nuxt-facebook-pixel-module#12]
**Is your feature request related to a problem? Please describe.**
To be fully compliant with the GDPR, we would be able to manage our options.
It would be nice to have an option to disable the track.

**Describe the solution you'd like**
As an `enable` function is provided, it would be nice to have a `disable` one! 😊

Thanks!

**Comment by dappiu** [comment]
You can't un-track a sent event, so if you want to be compliant with GDPR you'll have to:
1) Start with `facebook.disabled = true` in nuxt.config.js
2) Ask the user for consent
3) If the user give consent, call $fb.enable()

If you start with disabled=false then the plugin sends the PageView event on load and you can't undo this (i.e. a disable() method is not possible).

**Comment by adamwardecki** [comment]
What if the user gives consent but decides to change his settings and opt-out of Fb tracking? I have a use-case where I'd like to use your module with `nuxt-cookie-control` https://codesandbox.io/s/vkwqmm577 and I'm afraid it's not possible atm.

**Comment by WilliamDASILVA** [comment]
Hello there,

Thanks for opening this issue!
This feature has been released in the `v1.4.0` version.

Let me know if that helps you.
