### ISSUE TITLE
Set manual only mode

### ISSUE THREAD

**Issue by madsh93** [WilliamDASILVA/nuxt-facebook-pixel-module#17]
By default Facebook sends random events, such as Subscribe Button Click. It does so by checking for buttons, and automatically add an event to this button.

It is possible to change the script to only allow manual events

````
// Line to enable Manual Only mode.
fbq('set', 'autoConfig', false, 'FB_PIXEL_ID'); 
````
See documentation here:
https://developers.facebook.com/docs/facebook-pixel/advanced/#automatic-configuration

Would it be possible to add an option in the module, to:
````
  facebook: {
    /* module options */
    track: 'PageView',
    pixelId: 'FACEBOOK_PIXEL_ID',
    disabled: false,
    manualMode: true
  },
````

**Comment by WilliamDASILVA** [comment]
Hello,

Thanks for opening this issue!
This feature has been released in the `v1.4.0` version.

Let me know if that helps you.
