### ISSUE TITLE
Allow for optional parameters to be send with events

### ISSUE THREAD

**Issue by papoms** [WilliamDASILVA/nuxt-facebook-pixel-module#8]
Facebook (optionally) accepts parameters for standard and custom events. 

> Parameters are optional, JSON-formatted objects that you can include when tracking standard and custom events. They allow you to provide additional information about your website visitors' actions. Once tracked, parameters can be used to further define any custom audiences you create.
> To include a parameter object with a standard or custom event, format your parameter data as an object using JSON, then include it as the third function parameter when calling the fbq('track') or fbq('trackCustom') functions.

https://developers.facebook.com/docs/facebook-pixel/implementation/conversion-tracking#parameters

I would like to add that to the corresponding functions in this Modules.

**Comment by WilliamDASILVA** [comment]
Hello @papoms,

Thanks for reporting the issue. It has been merged and released under the `v1.3.0` tag!
